
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo1
  region: ap-southeast-1

managedNodeGroups:
  - name: demo1-ng1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 30
    amiFamily: AmazonLinux2
    # ami: ami-073998ba87e205747
    ssh: # use existing EC2 key
      publicKeyName: eason_person
    

